### ISSUE TITLE
Change uiduid to udidudid [maybe]

### ISSUE THREAD

**Issue by captinc** [Diatrus/uikittools-ng#2]
You _might_ want to change `uiduid` to `udidudid` for consistency with the `ecidecid` command. This is a maybe though - you don't want to rename it and break other things. Alternatively, you could make uiduid an alias to udidudid to maintain compatibility

**Comment by Diatrus** [comment]
I don't think this change is really relevant. Their meanings are essentially the same, Unique Identifier vs Unique Device Identifier.
